import type { Metadata } from 'next';
import './globals.css';
import Link from 'next/navigation';

export const metadata: Metadata = {
  title: 'CommuniSense',
  description: 'Community-adaptive moderation layer generated by Gemini',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav style={{ padding: '20px 24px', borderBottom: '1px solid var(--border-subtle)', background: 'var(--glass-bg)', backdropFilter: 'blur(10px)', position: 'sticky', top: 0, zIndex: 100, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div style={{ fontWeight: 700, fontSize: '1.2rem', display: 'flex', alignItems: 'center', gap: 8 }}>
            <span style={{ width: 12, height: 12, background: 'var(--accent-primary)', borderRadius: '50%', display: 'inline-block' }}></span>
            CommuniSense
          </div>
          <div style={{ display: 'flex', gap: 24, fontSize: '0.9rem', fontWeight: 500 }}>
            {/* Simple static links for MVP navigation */}
            <a href="/" style={{ color: 'var(--text-secondary)', textDecoration: 'none' }}>Ingest</a>
            <a href="/profile" style={{ color: 'var(--text-secondary)', textDecoration: 'none' }}>Profile</a>
            <a href="/constitution" style={{ color: 'var(--text-secondary)', textDecoration: 'none' }}>Constitution</a>
            <a href="/playground" style={{ color: 'var(--text-secondary)', textDecoration: 'none' }}>Playground</a>
            <a href="/compare" style={{ color: 'var(--accent-primary)', textDecoration: 'none' }}>Compare Mode</a>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
